name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Check
        run: nix flake check

      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          generate_release_notes: true

  build:
    needs: check
    strategy:
      matrix:
        target: [x86_64-windows, x86_64-linux, aarch64-linux, aarch64-darwin]
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#deno-${{ matrix.target }} -o bundle

      - if: matrix.target != 'x86_64-windows'
        name: Package (tar.xz)
        run: tar -cJf "node-template-${GITHUB_REF_NAME#v}-${{ matrix.target }}.tar.xz" bundle

      - if: matrix.target == 'x86_64-windows'
        name: Package (zip)
        run: zip -r "node-template-${GITHUB_REF_NAME#v}-${{ matrix.target }}.zip" bundle

      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            node-template-*-${{ matrix.target }}.tar.xz
            node-template-*-${{ matrix.target }}.zip

  container:
    needs: check
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#toDockerStream -o result

      - name: Setup skopeo
        run: |
          mkdir -p ~/.config/containers
          curl -L -o ~/.config/containers/policy.json https://raw.githubusercontent.com/containers/image/main/default-policy.json
          skopeo login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Release
        run: |
          ./result | gzip --fast | skopeo copy \
            docker-archive:/dev/stdin \
            "docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}-${{ steps.init.outputs.system }}"

  manifest:
    needs: build-container
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Setup podman
        run: |
          mkdir -p ~/.config/containers
          curl -L -o ~/.config/containers/policy.json https://raw.githubusercontent.com/containers/image/main/default-policy.json

          # fix for https://github.com/containers/podman/issues/24642#issuecomment-2582629496
          PODMAN_PATH=$(which podman || echo /usr/local/bin/podman)
          sudo sed -Ei "s!^profile podman /usr/bin/podman !profile podman $PODMAN_PATH !" /etc/apparmor.d/podman || true

          podman login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Create manifest
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}}"

          podman manifest create "${IMAGE}"
          podman manifest add "${IMAGE}" "${IMAGE}-x86_64-linux" --arch amd64 --os linux
          podman manifest add "${IMAGE}" "${IMAGE}-aarch64-linux" --arch arm64 --os linux
          podman manifest add "${IMAGE}" "${IMAGE}-aarch64-darwin" --arch arm64 --os darwin
          podman manifest push --all "${IMAGE}" "docker://${IMAGE}"
          podman manifest push --all "${IMAGE}" "docker://ghcr.io/${{ github.repository }}:latest"
