name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Check
        run: nix flake check

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          generate_release_notes: true

  linux-amd64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Build
        run: nix build

      - name: Bundle
        run: nix bundle --bundler github:DavHau/nix-portable#zstd-max -o result

      - name: Rename
        id: rename
        run: |
          FILE_LINK=$(find -L result -type f -print -quit)
          FILE_REAL=$(readlink -f "${FILE_LINK}")
          ln -s "${FILE_REAL}" template-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-linux-amd64

      - name: Export build
        run: nix nario export --format 2 --recursive > linux-amd64.nario

      - name: Upload build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: linux-amd64
          path: linux-amd64.nario

  linux-amd64-deb:
    needs: linux-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: linux-amd64

      - name: Import build
        run: nix nario import --no-check-sigs < linux-amd64.nario

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toDEB -o result
          cp result/*.deb template-linux-amd64.deb

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-linux-amd64.deb

  linux-amd64-rpm:
    needs: linux-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: linux-amd64

      - name: Import build
        run: nix nario import --no-check-sigs < linux-amd64.nario

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toRPM -o result
          cp result/*.rpm template-linux-amd64.rpm

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-linux-amd64.rpm

  linux-amd64-container:
    needs: linux-amd64
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: linux-amd64

      - name: Import build
        run: nix nario import --no-check-sigs < linux-amd64.nario

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#toDockerStream -o result

      - name: Release
        run: >
          ./result |
          gzip --fast |
          skopeo copy
          --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
          docker-archive:/dev/stdin
          docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}-amd64

  linux-arm64:
    needs: release
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Build
        run: nix build

      - name: Bundle
        run: nix bundle --bundler github:DavHau/nix-portable#zstd-max -o result

      - name: Rename
        id: rename
        run: |
          FILE_LINK=$(find -L result -type f -print -quit)
          FILE_REAL=$(readlink -f "${FILE_LINK}")
          ln -s "${FILE_REAL}" template-linux-arm64

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-linux-arm64

      - name: Export build
        run: nix nario export --format 2 --recursive > linux-arm64.nario

      - name: Upload build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: linux-arm64
          path: linux-arm64.nario

  linux-arm64-container:
    needs: linux-arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: linux-arm64

      - name: Import build
        run: nix nario import --no-check-sigs < linux-arm64.nario

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#toDockerStream -o result

      - name: Release
        run: >
          ./result |
          gzip --fast |
          skopeo copy
          --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
          docker-archive:/dev/stdin
          docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}-arm64

  macos-arm64:
    needs: release
    runs-on: macos-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Build
        run: nix build

      - name: Bundle
        run: nix bundle --bundler github:DavHau/nix-portable#zstd-max -o result

      - name: Rename
        id: rename
        run: |
          FILE_LINK=$(find -L result -type f -print -quit)
          FILE_REAL=$(readlink -f "${FILE_LINK}")
          ln -s "${FILE_REAL}" template-macos-arm64

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-macos-arm64

      - name: Export build
        run: nix nario export --format 2 --recursive > macos-arm64.nario

      - name: Upload build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: macos-arm64
          path: macos-arm64.nario
