name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Check
        run: nix flake check

  release:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          generate_release_notes: true

  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-26]
    needs: release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          SYSTEM=$(nix eval --impure --raw --expr 'builtins.currentSystem')
          echo "system=${SYSTEM}" >> $GITHUB_OUTPUT

          NAME=$(nix eval --raw .#packages."${SYSTEM}".default.name)
          echo "name=${NAME}-${SYSTEM}" >> $GITHUB_OUTPUT

      - name: Build
        run: nix build

      - name: Bundle
        run: nix bundle --bundler github:DavHau/nix-portable#zstd-max -o result

      - name: Rename
        id: rename
        run: |
          FILE_LINK=$(find -L result -type f -print -quit)
          FILE_REAL=$(readlink -f "${FILE_LINK}")
          ln -s "${FILE_REAL}" "${{ steps.package.outputs.name }}"

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: ${{ steps.package.outputs.name }}

      - name: Export build
        run: nix nario export --format 2 --recursive > "${{ steps.package.outputs.system }}.nario"

      - name: Upload build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ steps.package.outputs.system }}
          path: ${{ steps.package.outputs.system }}.nario

  build-deb:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          SYSTEM=$(nix eval --impure --raw --expr 'builtins.currentSystem')
          echo "system=${SYSTEM}" >> $GITHUB_OUTPUT

          NAME=$(nix eval --raw .#packages."${SYSTEM}".default.name)
          echo "name=${NAME}-${SYSTEM}" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ steps.package.outputs.system }}

      - name: Import build
        run: nix nario import --no-check-sigs < "${{ steps.package.outputs.system }}.nario"

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toDEB -o result
          cp result/*.deb "${{ steps.package.outputs.name }}.deb"

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: ${{ steps.package.outputs.name }}.deb

  build-rpm:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          SYSTEM=$(nix eval --impure --raw --expr 'builtins.currentSystem')
          echo "system=${SYSTEM}" >> $GITHUB_OUTPUT

          NAME=$(nix eval --raw .#packages."${SYSTEM}".default.name)
          echo "name=${NAME}-${SYSTEM}" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ steps.package.outputs.system }}

      - name: Import build
        run: nix nario import --no-check-sigs < "${{ steps.package.outputs.system }}.nario"

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toRPM -o result
          cp result/*.rpm "${{ steps.package.outputs.name }}.rpm"

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: ${{ steps.package.outputs.name }}.rpm

  build-container:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@e2fa614def25ff8e1ba97f43825b1dc198792423 # v1.8.13
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          SYSTEM=$(nix eval --impure --raw --expr 'builtins.currentSystem')
          echo "system=${SYSTEM}" >> $GITHUB_OUTPUT

          NAME=$(nix eval --raw .#packages."${SYSTEM}".default.name)
          echo "name=${NAME}-${SYSTEM}" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ steps.package.outputs.system }}

      - name: Import build
        run: nix nario import --no-check-sigs < "${{ steps.package.outputs.system }}.nario"

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#toDockerStream -o result

      - name: Release
        run: >
          ./result |
          gzip --fast |
          skopeo copy
          --dest-creds="${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
          docker-archive:/dev/stdin
          "docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}-${{ steps.package.outputs.system }}"
