name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14

      - name: Check
        run: nix flake check

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          generate_release_notes: true

  build:
    needs: check
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          NAME=$(nix eval --raw .#packages."${{ steps.init.outputs.system }}".default.name)
          echo "name=${NAME}-${{ steps.init.outputs.system }}" >> $GITHUB_OUTPUT

      - name: Build
        run: nix build

      - name: Export build
        run: nix nario export --format 2 --recursive > "${{ steps.init.outputs.system }}.nario"

      - name: Upload build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ steps.init.outputs.system }}
          path: ${{ steps.init.outputs.system }}.nario

  build-static:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          NAME=$(nix eval --raw .#packages."${{ steps.init.outputs.system }}".default.name)
          echo "name=${NAME}-${{ steps.init.outputs.system }}" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ steps.init.outputs.system }}

      - name: Import build
        run: nix nario import --no-check-sigs < "${{ steps.init.outputs.system }}.nario"

      - name: Bundle
        run: nix bundle --bundler github:DavHau/nix-portable#zstd-max -o result

      - name: Rename
        id: rename
        run: |
          FILE_LINK=$(find -L result -type f -print -quit)
          FILE_REAL=$(readlink -f "${FILE_LINK}")
          ln -s "${FILE_REAL}" "${{ steps.package.outputs.name }}"

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: ${{ steps.package.outputs.name }}

  build-deb:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          NAME=$(nix eval --raw .#packages."${{ steps.init.outputs.system }}".default.name)
          echo "name=${NAME}-${{ steps.init.outputs.system }}" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ steps.init.outputs.system }}

      - name: Import build
        run: nix nario import --no-check-sigs < "${{ steps.init.outputs.system }}.nario"

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toDEB -o result
          cp result/*.deb "${{ steps.package.outputs.name }}.deb"

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: ${{ steps.package.outputs.name }}.deb

  build-rpm:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          NAME=$(nix eval --raw .#packages."${{ steps.init.outputs.system }}".default.name)
          echo "name=${NAME}-${{ steps.init.outputs.system }}" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ steps.init.outputs.system }}

      - name: Import build
        run: nix nario import --no-check-sigs < "${{ steps.init.outputs.system }}.nario"

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toRPM -o result
          cp result/*.rpm "${{ steps.package.outputs.name }}.rpm"

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: ${{ steps.package.outputs.name }}.rpm

  build-container:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Get package info
        id: package
        run: |
          NAME=$(nix eval --raw .#packages."${{ steps.init.outputs.system }}".default.name)
          echo "name=${NAME}-${{ steps.init.outputs.system }}" >> $GITHUB_OUTPUT

          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          echo "os=${OS}" >> $GITHUB_OUTPUT

          ARCH=$(uname -m)
          case "${ARCH}" in
            x86_64) ARCH="amd64" ;;
            aarch64) ARCH="arm64" ;;
          esac
          echo "arch=${ARCH}" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ steps.init.outputs.system }}

      - name: Import build
        run: nix nario import --no-check-sigs < "${{ steps.init.outputs.system }}.nario"

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#toDockerStream -o result

      - name: Release
        run: >
          ./result |
          gzip --fast |
          skopeo --insecure-policy copy
          --dest-creds="${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
          docker-archive:/dev/stdin
          "docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}-${{ steps.package.outputs.os }}-${{ steps.package.outputs.arch }}"

  manifest:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@a4440ed9daa3faedcfc8cd491dbcfa5e38d84156 # v1.8.14
        with:
          shell: release

      - name: Create manifest
        run: |
          manifest-tool \
            --username "${{ github.actor }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            push from-args \
            --platforms linux/amd64,linux/arm64,darwin/arm64 \
            --template "docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}-OS-ARCH" \
            --tags latest \
            --target "docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}}"
